### ISSUE TITLE
How to run example com.farata.lang.async.examples.bank.AsyncAwaitBusinessServicesExample?

### ISSUE THREAD

**Issue by minhkiller** [vsilaev/java-async-await#1]
Hi Valery,

I have issue when running the example com.farata.lang.async.examples.bank.AsyncAwaitBusinessServicesExample

> /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50846,suspend=y,server=n -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/tools.jar:/Users/mtran/projects/study/java/java-async-await/com.farata.lang.async.examples/target/classes:/Users/mtran/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/mtran/projects/study/java/java-async-await/com.farata.lang.async.api/target/classes:/Users/mtran/.m2/repository/net/tascalate/javaflow/net.tascalate.javaflow.api/2.0-SNAPSHOT/net.tascalate.javaflow.api-2.0-SNAPSHOT.jar:/Users/mtran/.m2/repository/net/javacrumbs/completion-stage/completion-stage/0.0.9/completion-stage-0.0.9.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.farata.lang.async.examples.bank.AsyncAwaitBusinessServicesExample
> Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
> Connected to the target VM, address: '127.0.0.1:50846', transport: 'socket'
> Mon Jul 11 21:57:31 AEST 2016 START ITERATION #1
> Exception in thread "main" java.lang.IllegalStateException: Method call must be replaced by bytecode enhancer
> 	at com.farata.lang.async.api.AsyncCall.asyncResult(AsyncCall.java:36)
> 	at com.farata.lang.async.examples.bank.MoneyWithdrawalTask$1DemoPrint.go(MoneyWithdrawalTask.java:36)
> 	at com.farata.lang.async.examples.bank.MoneyWithdrawalTask.execute(MoneyWithdrawalTask.java:42)
> 	at com.farata.lang.async.examples.bank.AsyncAwaitBusinessServicesExample.main(AsyncAwaitBusinessServicesExample.java:18)
> Disconnected from the target VM, address: '127.0.0.1:50846', transport: 'socket'
> Inner Class 510.5 com.farata.lang.async.examples.bank.MoneyWithdrawalTask@4f47d241
> 
> Process finished with exit code 1

How do i instrument the example project with javaflow?

Thanks for your help.

Regards,
Minh Tran

**Comment by vsilaev** [comment]
It looks like you haven't specified JavaAgent for bytecode transformation.
You should use additional JVM argument:
 `-javaagent:../com.farata.lang.async.tools.javaagent/target/AsyncAwaitInstrumentationAgent.jar`

The agent is compiled as a part of Maven build (relative path to artifact is assumed above). Compile-time bytecode instrumentation is not available yet.

**Comment by minhkiller** [comment]
Thanks Valery,

I used this command to build the agent jar file: `mvn install`
Then passed the VM option when running **com.farata.lang.async.examples.bank.AsyncAwaitBusinessServicesExample**
`-javaagent:-javaagent:<PATH-TO-MAVEN-REPO>/repository/com/farata/lang/async/com.farata.lang.async.tools.javaagent/1.0-SNAPSHOT/com.farata.lang.async.tools.javaagent-1.0-SNAPSHOT.jar`
